baseurl: "/"
title: "Fractal"
main_js: "assets/js/main.js"
params:
  palette: blue
  palettes:
    blue:
      sass:
        color: "#4696e5"
    magenta:
      sass:
        color: "#db5c7a"
    purple:
      sass:
        color: "#786dc2"
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
#templates:
#  body_class: "is-preload"
